version: "3"
services:
  fingerprint-photo-matcher:
    container_name: fingerprint-photo-matcher
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./dockerfile
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    volumes:
      - ./:/home/fingerprint-photo-matcher/code/
    ports:
      - 8080:8080

